### ISSUE TITLE
Remove "Oztro" branding

### ISSUE THREAD

**Issue by rmehta** [ESS-LLP/oztro#1]
Use generic names so others feel comfortable using it!

**Comment by rkurungadam** [comment]
Sure.. We'll make it generic enough. They used custom translations to remove oztro in the shared demo instance. Not sure if there are others looking for this use case, have seen some posts in discuss though, guess I should find and tag people :-)
Thanks

**Comment by woakes070048** [comment]
why not merge this into the core project?

**Comment by pjamsheer** [comment]
Removed "Oztro" branding

**Comment by elan-k** [comment]
@pjamsheer & @rmehta : why not merging this into the core project since it's a very much useful feature. 

Or Any option to install as an App on frappecloud.com ?
