### ISSUE TITLE
Some minor questions.

### ISSUE THREAD

**Issue by asharamseervi** [ESS-LLP/oztro#2]
Believe me, you guys are doing great. I found this today after going through many many threads on the forum.

Some question after getting this app:
- Master is far far behind than Develop branch. Why still not merged to Master?
- Is there any difference between Workstation & Department? I have some department in Manufacturing Module which is not showing in Process Manufacturing. Please help with this.
- Some process in production has to skip while another process has to be done with the product, as mentioned in the thread raised by me here: https://discuss.erpnext.com/t/how-to-skip-operations-in-production/31811. Process Manufacturing app will helpful in that scenario? 
- Also, This app will be very beneficial to ERPNext users, are you willing to contribute it to the core? ERPNext v10 is releasing soon, you guys may also raise a PR for that.

Sorry, for such questions, you guys are very senior and doing great. Still, thought why not to alarm you.
EDIT: Can you upload video on Youtube and link on readme, instead of GIF. Requesting because, GIF contains more than 4 minutes, and the drawback is we can't pause/resume it.

**Comment by asharamseervi** [comment]
Hello Team, I am testing and playing with Process Manufacturing App. I just faced an issue, I'm not exactly reporting you in a technical way, so to raise my voice, I tried to record a video so, it will clear in one sight and help you to fix that issue.
You may found that video here: https://youtu.be/gfPjoEwNxgw

Basically, In entry I'm getting item name as double in first entry, if I remove first and hence, the second entry will also become first. It will happen same.

**Comment by asharamseervi** [comment]
I had given many trials even with clean ERPNext instance, that on first row of **Oztro Process**, making some conflict and hence, it'll not helping to complete **Oztro Process Order**.
I tried with Master as well as Develop branch, both are having the same issue. Or, might I'm missing something. Will you look into this and fix the issue? (I'm not so much proficient & experienced with Python & JS)

At Oztro Process:
Screenshot: 1
![erpnext-oztro-issue-1](https://user-images.githubusercontent.com/5942572/34317688-2176763c-e7da-11e7-9ff7-b5e18b513d98.PNG)

Screenshot: 2
![erpnext-oztro-issue-2](https://user-images.githubusercontent.com/5942572/34317699-321ee078-e7da-11e7-9112-e1179a89fe2d.PNG)

and Screenshot: 3 while Oztro Process Order: (I had inserted quantity as 1 still, it will produce Validation Error in Screenshot 4)
![erpnext-oztro-issue-3](https://user-images.githubusercontent.com/5942572/34317728-e8731ee8-e7da-11e7-9426-2d1ea230a099.PNG)

and Finally Validation Error, even though I had inserted produced the quantity as Screenshot 3.
![erpnext-oztro-issue-4](https://user-images.githubusercontent.com/5942572/34317747-5df10b94-e7db-11e7-9fbf-a9ed54084ce0.PNG)

I would like to tag you for notification, sorry for bothering. @akurungadam @rkurungadam @pjamsheer @ESSLLP

**Comment by rkurungadam** [comment]
Hi, You are producing and consuming the same Item, just wonder if this is a valid use case. Validation for this is not present now, but can be added. BTW go with the master branch, in develop the stock entries are created and submitted automatically.
Thanks

**Comment by asharamseervi** [comment]
Thank you so much @rkurungadam for responding promptly.

Yes, when I consuming the same product and producing another product, everything is fine. I omit my mistake.But, will you help me, in case when same sub-assembly item which already cut in cutting operation from a metal sheet, after that same product going to bending(if required) & fabrication. After fabrication, a group of sub-assembly item producing the final product.

So, there is not necessary of bending process for each and every item, but most of them do. So, can we manage it with process manufacturing?

**Comment by rkurungadam** [comment]
Hi,
I am not sure if you should be using Process Manufacturing. If it is discrete manufacturing and is about skipping operations in Production Order you should consider enhancing ERPNext Manufacturing Module itself.
If an Item returns after a process then ideally it should be different item, so there is better stock management, but anyways validation for your usecase can be added.
And please pull out the youtube video, don't think it is relevant anymore.
Thanks
