### ISSUE TITLE
ESS-LLP/process manufacturing

### ISSUE THREAD

**Issue by Dottess** [ESS-LLP/oztro#4]
Hi guys.
Please assist.
From the process manufacturing app,I noticed that a user defines their production processes. Then produce a production order which consists of the raw materials,finished products and scrap together with their quantities.
I need help on how to include:
-how much of the products is produced from the available raw materials.
-to know  which quantity was waste/scrap.

**Comment by rkurungadam** [comment]
Product and scrap qty is know and entered only in real time, that's in the production process.

**Comment by mikemayaka** [comment]
Hi,
I have entered the raw material quantities required on the first screen of production order but when I click on start, another screen pops up forcing me to re-enter the same values. How do I disable the popup screen?
![production-order](https://user-images.githubusercontent.com/21366395/51967659-f1a44800-2480-11e9-882a-3a503faca928.png)
![po-popup-screen](https://user-images.githubusercontent.com/21366395/51967673-fd900a00-2480-11e9-9780-f94ca3e7d735.png)
